### PR TITLE
added and changed connectivity to build 77050 Animal Crossing set

### PR DESCRIPTION
**Pull request by ZPhilo**

### CODE REVIEW

**Comment by RolandMelkert** [comment]
You seem to have used an older LDCad during editing or disabled the auto shadow feature as most of the headers use the wrong author. There also seem to be two different versions of your own name. Older files donated by you use the long one.

Could you correct this before I merge it?

**Comment by ZPhilo** [comment]
I thought I did it right, but I'll check again ;)

**Comment by ZPhilo** [comment]
Hopefully corrected the problems!

**Comment by RolandMelkert** [comment]
Thanks, I only fixed some newer details with Beta 2.
Will merge it next.

**Comment by ZPhilo** [comment]
> Thanks, I only fixed some newer details with Beta 2. Will merge it next.

Beta 2 is not yet published, right?

**Comment by RolandMelkert** [comment]
Not yet, still looking into some of the snapping problems and adding the avatar meta.

Shadow wise the only difference is some support tools for handling unofficial part shadows.

**Pull request merged**
